/**
 * Outlook Calendar MCP Server catalog entry.
 * Generated from discovery-output.json — 13 tools.
 * Source of truth: MCP protocol discovery, not guesses.
 */

import type { IMcpCatalogEntry } from '../McpServerCatalog';
import { GATEWAY_BASE } from './constants';

export const CALENDAR_SERVER: IMcpCatalogEntry = {
  id: 'mcp_CalendarTools',
  name: 'Outlook Calendar',
  description: 'Create events, check availability, manage meetings',
  scope: 'McpServers.Calendar.All',
  urlTemplate: `${GATEWAY_BASE}/mcp_CalendarTools`,
  tools: [
    { name: 'ListEvents', description: 'Retrieve a list of events for the user with a given criteria - start and end datetimes, title of the meeting, attendee emails etc. This returns only the master event for recurring meetings.', inputSchema: {"type":"object","properties":{"startDateTime":{"type":"string","description":"Start date/time in ISO 8601 format (e.g., '2026-01-15T09:00:00Z'). Default : user'sCurrentTime."},"endDateTime":{"type":"string","description":"End date/time in ISO 8601 format (e.g., '2026-01-15T17:00:00Z'). Default : currentTime + 90 days."},"meetingTitle":{"type":"string","description":"Meeting title to search by"},"attendeeEmails":{"type":"object"},"timeZone":{"type":"string","description":"timezone for the event (e.g., 'Pacific Standard Time'). Default : current user's timezone."},"select":{"type":"string","description":"Comma-separated list of properties to return"},"top":{"type":"object"},"orderby":{"type":"string","description":"Property name to sort results by (e.g., 'displayName', 'jobTitle'). Meeting startTime is specified if not used."}}}, blockHint: 'list-items' as const },
    { name: 'ListCalendarView', description: 'Retrieve events from a user\'s calendar view with recurring events expanded into individual instances. Use this whenever you need to find user\'s meetings in general, or one meeting instance of a rec...', inputSchema: {"type":"object","properties":{"userIdentifier":{"type":"string","description":"User identifier - can be email, Entra ID (GUID), display name, or 'me' for current user. Defaults to 'me' if not specified."},"startDateTime":{"type":"string","description":"Start date/time in ISO 8601 format (e.g., '2026-01-15T09:00:00'). Default: current time of current user"},"endDateTime":{"type":"string","description":"End date/time in ISO 8601 format (e.g., '2026-01-15T17:00:00'). Default: current time of current user + 15 days"},"timeZone":{"type":"string","description":"Time zone for the event (e.g., 'Pacific Standard Time'). Default : current user's timezone."},"subject":{"type":"string","description":"Search term to filter events by subject/title. Use this to find specific meetings by name."},"select":{"type":"string","description":"Comma-separated list of properties to return"},"top":{"type":"object"},"orderby":{"type":"string","description":"Property name to sort results by (e.g., 'start/dateTime'). Default is 'start/dateTime'."}},"required":["userIdentifier"]}, blockHint: 'list-items' as const },
    { name: 'CreateEvent', description: 'Create a new calendar event. Can provide names or email addresses for attendees (names will be resolved to emails). If time is provided, schedules even if there are conflicts. Default duration is 3...', inputSchema: {"type":"object","properties":{"subject":{"type":"string","description":"Event title/subject"},"attendeeEmails":{"type":"array","description":"List of email or userPrincipalNames of attendees.Please fetch the email addresses of the users before making this call.","items":{"type":"string"}},"startDateTime":{"type":"string","description":"Start date/time in ISO 8601 format (e.g., '2026-01-15T09:00:00')"},"endDateTime":{"type":"string","description":"End date/time in ISO 8601 format (e.g., '2026-01-15T09:30:00')"},"timeZone":{"type":"string","description":"Time zone for the event (e.g., 'Pacific Standard Time'). Default is current user's timezone."},"bodyContent":{"type":"string","description":"Event body/description content"},"bodyContentType":{"type":"string","description":"Body content type: 'Text' or 'HTML'. Default is 'Text'."},"location":{"type":"string","description":"Event location display name"},"isOnlineMeeting":{"type":"boolean","description":"Whether to create as an online meeting. Defaults to true."},"onlineMeetingProvider":{"type":"string","description":"Online meeting provider: 'teamsForBusiness', 'skypeForBusiness', 'skypeForConsumer'. Defaults to 'teamsForBusiness'."},"allowNewTimeProposals":{"type":"object"},"recurrence":{"type":"object"},"importance":{"type":"string","description":"Event importance: 'low', 'normal', 'high'. Default is 'normal'."},"sensitivity":{"type":"string","description":"Event sensitivity: 'normal', 'personal', 'private', 'confidential'. Default is 'normal'."},"showAs":{"type":"string","description":"Free/busy status to show: 'free', 'tentative', 'busy', 'oof', 'workingElsewhere', 'unknown'. Default is 'busy'."},"responseRequested":{"type":"boolean","description":"Whether a response is requested from invitees. Default is true."}},"required":["subject","attendeeEmails","startDateTime","endDateTime"]}, blockHint: 'info-card' as const },
    { name: 'UpdateEvent', description: 'Update an existing calendar event. Can add or remove attendees by providing names or email addresses (names will be resolved to emails automatically).', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to update"},"subject":{"type":"string","description":"Updated event title/subject"},"startDateTime":{"type":"string","description":"Updated start date/time in ISO 8601 format"},"endDateTime":{"type":"string","description":"Updated end date/time in ISO 8601 format"},"timeZone":{"type":"string","description":"Updated Time zone for the event (e.g., 'Pacific Standard Time')."},"attendeesToAdd":{"type":"array","description":"List of attendee email addresses or names to add","items":{"type":"string"}},"attendeesToRemove":{"type":"array","description":"List of attendee email addresses or names to remove","items":{"type":"string"}},"body":{"type":"string","description":"Updated event body/description"},"location":{"type":"string","description":"Updated event location"},"recurrence":{"type":"object"},"importance":{"type":"string","description":"Updated event importance: 'low', 'normal', 'high'"},"sensitivity":{"type":"string","description":"Updated event sensitivity: 'normal', 'personal', 'private', 'confidential'"},"showAs":{"type":"string","description":"Updated free/busy status to show: 'free', 'tentative', 'busy', 'oof', 'workingElsewhere', 'unknown'"},"responseRequested":{"type":"object"}},"required":["eventId"]}, blockHint: 'info-card' as const },
    { name: 'DeleteEventById', description: 'Delete a calendar event. Retrieve the event details first to extract the ID, then pass it to be deleted.', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to delete."}},"required":["eventId"]}, blockHint: 'info-card' as const },
    { name: 'FindMeetingTimes', description: 'Find meeting times that work for all attendees. Suggests meeting times based on organizer and attendee availability. Can provide names or email addresses for attendees (names will be resolved to em...', inputSchema: {"type":"object","properties":{"userIdentifier":{"type":"string","description":"User identifier for the organizer - can be email, Entra ID (GUID), display name, or 'me' for current user. Defaults to 'me' if not specified."},"attendeeEmails":{"type":"array","description":"List of attendee email addresses or names","items":{"type":"string"}},"meetingDuration":{"type":"string","description":"Meeting duration in ISO 8601 format (e.g., 'PT1H' for 1 hour, 'PT30M' for 30 minutes). Required."},"startDateTime":{"type":"string","description":"Start of the time range in ISO 8601 format (e.g., '2026-01-15T09:00:00'). Defaults to current time."},"endDateTime":{"type":"string","description":"End of the time range in ISO 8601 format (e.g., '2026-01-15T17:00:00'). Defaults to start time + 7 days."},"timeZone":{"type":"string","description":"Time zone (e.g., 'Pacific Standard Time'). Default is current user's timezone."},"maxCandidates":{"type":"object"},"isOrganizerOptional":{"type":"boolean","description":"Whether the organizer's attendance is optional. Default is false."},"returnSuggestionReasons":{"type":"boolean","description":"Whether to return reasons for each suggestion. Default is true."},"minimumAttendeePercentage":{"type":"object"}}}, blockHint: 'list-items' as const },
    { name: 'AcceptEvent', description: 'Accept a calendar event invitation. Optionally include a comment with the acceptance.', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to accept"},"comment":{"type":"string","description":"Optional comment to include with the acceptance"},"sendResponse":{"type":"boolean","description":"Whether to send a response to the organizer. Defaults to true."}},"required":["eventId"]}, blockHint: 'info-card' as const },
    { name: 'TentativelyAcceptEvent', description: 'Tentatively accept a calendar event invitation. Optionally include a comment with the tentative acceptance.', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to tentatively accept"},"comment":{"type":"string","description":"Optional comment to include with the tentative acceptance"},"sendResponse":{"type":"boolean","description":"Whether to send a response to the organizer. Defaults to true."}},"required":["eventId"]}, blockHint: 'info-card' as const },
    { name: 'DeclineEvent', description: 'Decline a calendar event invitation. Optionally include a comment with the decline.', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to decline"},"comment":{"type":"string","description":"Optional comment to include with the decline"},"sendResponse":{"type":"boolean","description":"Whether to send a response to the organizer. Defaults to true."}},"required":["eventId"]}, blockHint: 'info-card' as const },
    { name: 'CancelEvent', description: 'Cancel a calendar event. Only the event organizer can cancel an event. This will send cancellation notifications to all attendees.', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to cancel"},"comment":{"type":"string","description":"Optional comment to include with the cancellation"}},"required":["eventId"]}, blockHint: 'info-card' as const },
    { name: 'ForwardEvent', description: 'Forward a calendar event to other recipients. Can provide names or email addresses for recipients (names will be resolved to emails).', inputSchema: {"type":"object","properties":{"eventId":{"type":"string","description":"The ID of the event to forward"},"recipientEmails":{"type":"array","description":"List of recipient email addresses or names to forward the event to","items":{"type":"string"}},"comment":{"type":"string","description":"Optional comment to include with the forwarded event"}},"required":["eventId","recipientEmails"]}, blockHint: 'info-card' as const },
    { name: 'GetUserDateAndTimeZoneSettings', description: 'Get date and timezone settings for a user including time zone, date format, time format, working hours, and language preferences. Can provide name, email address, or use \'me\' for current user.', inputSchema: {"type":"object","properties":{"userIdentifier":{"type":"string","description":"User identifier - can be email, Entra ID (GUID), display name, or 'me' for current user. Defaults to 'me' if not specified."}}}, blockHint: 'info-card' as const },
    { name: 'GetRooms', description: 'Get all the meeting rooms defined in the user\'s tenant. Returns room names and email addresses.', inputSchema: {"type":"object","properties":{}}, blockHint: 'list-items' as const }
  ]
};
