/**
 * SharePoint Lists MCP Server catalog entry.
 * Generated from discovery-output.json — 13 tools.
 * Source of truth: MCP protocol discovery, not guesses.
 */

import type { IMcpCatalogEntry } from '../McpServerCatalog';
import { GATEWAY_BASE } from './constants';

export const LISTS_SERVER: IMcpCatalogEntry = {
  id: 'mcp_SharePointListsTools',
  name: 'SharePoint Lists',
  description: 'Create/manage SharePoint lists, columns, and items',
  scope: 'McpServers.SharepointLists.All',
  urlTemplate: `${GATEWAY_BASE}/mcp_SharePointListsTools`,
  tools: [
    { name: 'createList', description: 'Create a new SharePoint list on a site.', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The full site ID in format 'hostname,siteCollectionId,webId' (e.g., 'contoso.sharepoint.com,abc123,def456'). Get this from the 'id' property when q..."},"displayName":{"type":"string","description":"Display name of the list."},"columns":{"type":"array","description":"Optional column definitions.","items":{"type":"object"}},"list":{"type":"object","description":"List info such as template."}},"required":["siteId","displayName","list"]}, blockHint: 'info-card' as const },
    { name: 'createListColumn', description: 'Create a new column (columnDefinition) in a specific SharePoint list. You must provide the target siteId and listId, plus a valid column definition that specifies the column\'s name, display name, a...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The unique ID of the site (site-id)."},"listId":{"type":"string","description":"The unique ID (GUID or unique identifier) of the list."},"name":{"type":"string","description":"API/static name of the column (no spaces)."},"displayName":{"type":"string","description":"User-facing display name."},"description":{"type":"string"},"enforceUniqueValues":{"type":"boolean"},"hidden":{"type":"boolean"},"indexed":{"type":"boolean"},"required":{"type":"boolean"},"readOnly":{"type":"boolean"},"text":{"type":"object","description":"Text column settings."},"number":{"type":"object","description":"Number column settings."},"choice":{"type":"object","description":"Choice column settings."},"boolean":{"type":"object","description":"Boolean column settings."},"dateTime":{"type":"object","description":"Date and time column settings."},"personOrGroup":{"type":"object","description":"Person or Group column settings."},"lookup":{"type":"object","description":"Lookup column settings."},"hyperlinkOrPicture":{"type":"object","description":"Hyperlink or Picture column settings."}},"required":["siteId","listId","name"]}, blockHint: 'info-card' as const },
    { name: 'createListItem', description: 'Create a new ITEM (row/record) in a specific SharePoint LIST. SharePoint Hierarchy - You are creating at the ITEMS level: - SITE (e.g., \'HR Hiring Test\') - └── LIST (e.g., \'Job Openings\') └── ITEMS...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The full site ID in format 'hostname,siteCollectionId,webId' (e.g., 'contoso.sharepoint.com,abc123,def456'). Get this from the 'id' property when q..."},"listId":{"type":"string","description":"The unique ID (or URL-encoded name) of the list."},"fields":{"type":"object","description":"Request body: Key-value pairs of internal column names and their values. This becomes the entire request body as {\"fields\": {...}}. Include at leas..."}},"required":["siteId","listId","fields"]}, blockHint: 'info-card' as const },
    { name: 'deleteListColumn', description: 'Delete an existing columnDefinition from a specific SharePoint list. Provide siteId, listId, and columnId. This permanently removes the column from the list schema. If any of the required informati...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"Unique ID of the site."},"listId":{"type":"string","description":"Unique ID (GUID) of the list."},"columnId":{"type":"string","description":"Unique ID (GUID) of the column to delete."}},"required":["siteId","listId","columnId"]}, blockHint: 'info-card' as const },
    { name: 'deleteListItem', description: 'Delete an ITEM (row/record) from a SharePoint LIST. SharePoint Hierarchy - You are deleting at the ITEMS level: - SITE (e.g., \'HR Hiring Test\') - └── LIST (e.g., \'Job Openings\') └── ITEMS ← This to...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The full site ID in format 'hostname,siteCollectionId,webId' (e.g., 'contoso.sharepoint.com,abc123,def456'). Get this from the 'id' property when q..."},"listId":{"type":"string","description":"The unique ID of the list."},"itemId":{"type":"string","description":"The unique ID of the list item."},"ifMatch":{"type":"string","description":"Optional ETag for concurrency control (e.g., \"*\")."}},"required":["siteId","listId","itemId"]}, blockHint: 'info-card' as const },
    { name: 'editListColumn', description: 'Update an existing columnDefinition on a specific SharePoint list. Provide siteId, listId, and columnId. Body is partial—include only the properties you want to change (e.g., displayName, descripti...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"Unique ID of the site."},"listId":{"type":"string","description":"Unique ID (GUID) of the list."},"columnId":{"type":"string","description":"Unique ID (GUID) of the column to update."},"displayName":{"type":"string","description":"User-facing display name."},"description":{"type":"string","description":"Column description."},"hidden":{"type":"boolean","description":"If true, column is hidden."},"required":{"type":"boolean","description":"If true, a value is required."},"enforceUniqueValues":{"type":"boolean","description":"If true, values must be unique."},"indexed":{"type":"boolean","description":"If true, values are indexed."},"readOnly":{"type":"boolean","description":"If true, values cannot be changed."},"text":{"type":"object","description":"Update text column settings."},"number":{"type":"object","description":"Update number column settings."},"choice":{"type":"object","description":"Update choice column settings."},"dateTime":{"type":"object","description":"Update dateTime column settings."},"personOrGroup":{"type":"object","description":"Update personOrGroup column settings."},"lookup":{"type":"object","description":"Update lookup column settings."},"hyperlinkOrPicture":{"type":"object","description":"Update hyperlink or picture column settings."}},"required":["siteId","listId","columnId"]}, blockHint: 'info-card' as const },
    { name: 'getSiteByPath', description: 'Resolve a SharePoint site using its EXACT hostname and server-relative path. Use this tool ONLY when you have the complete site URL structure (e.g., hostname=\'contoso.sharepoint.com\' and path=\'site...', inputSchema: {"type":"object","properties":{"hostname":{"type":"string","description":"Host name of the SharePoint tenant, e.g., contoso.sharepoint.com."},"serverRelativePath":{"type":"string","description":"Server-relative path to the site (no leading slash in final URI section). Example: sites/Marketing"}},"required":["hostname","serverRelativePath"]}, blockHint: 'site-info' as const },
    { name: 'listListColumns', description: 'List column definitions (columnDefinition resources) for a specific SharePoint list. Requires siteId and listId. Supports OData params like $select, $top, and $skiptoken. If any of the required inf...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The unique ID of the site (site-id)."},"listId":{"type":"string","description":"The unique ID (GUID or unique identifier) of the list."},"select":{"type":"string","description":"Comma-separated list of properties to return (maps to $select)."},"filter":{"type":"string","description":"OData filter expression to restrict results (maps to $filter)."},"orderBy":{"type":"string","description":"Comma-separated list of properties to order by (maps to $orderby)."},"top":{"type":"number","description":"Page size (maps to $top)."},"skiptoken":{"type":"string","description":"Opaque token for paging to the next set (maps to $skiptoken)."}},"required":["siteId","listId"]}, blockHint: 'list-items' as const },
    { name: 'listListItems', description: 'Get ITEMS (rows/records) from a specific SharePoint LIST. Use this to retrieve data from within a list. SharePoint Hierarchy - You are at the ITEMS level: - SITE (e.g., \'HR Hiring Test\') - └── LIST...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The full site ID in format 'hostname,siteCollectionId,webId' (e.g., 'contoso.sharepoint.com,abc123,def456'). Get this from the 'id' property when q..."},"listId":{"type":"string","description":"The unique ID (or URL-encoded name) of the list."},"expand":{"type":"string","description":"OData $expand clause. Defaults to 'fields' so list item field values (column data) are returned without needing to specify it explicitly. Override ..."},"top":{"type":"number","description":"Optional page size."},"filter":{"type":"string","description":"Optional OData filter expression."},"select":{"type":"string","description":"Optional OData select clause."}},"required":["siteId","listId"]}, blockHint: 'list-items' as const },
    { name: 'listLists', description: 'Get all SharePoint LISTS available on a specific SITE. Use this to discover what lists exist within a SharePoint site. SharePoint Hierarchy: - SITE (e.g., \'HR Hiring Test\') ← You need the siteId fo...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The full site ID in format 'hostname,siteCollectionId,webId' (e.g., 'contoso.sharepoint.com,abc123,def456'). Get this from the 'id' property when q..."}},"required":["siteId"]}, blockHint: 'list-items' as const },
    { name: 'listSubsites', description: 'List child sites (subsites) for a given site.', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The unique ID of the site (or site-id, e.g., {hostname},{spsiteId},{spwebId})."}},"required":["siteId"]}, blockHint: 'selection-list' as const },
    { name: 'searchSitesByName', description: 'PRIMARY TOOL for finding SharePoint SITES (not lists) when the user provides a site NAME, TITLE, or partial name. IMPORTANT - SharePoint Hierarchy: - SITE (e.g., \'HR Hiring Test\', \'Marketing Site\')...', inputSchema: {"type":"object","properties":{"search":{"type":"string","description":"Display name or partial name/URL of the SharePoint site to search for."},"consistencyLevel":{"type":"string","description":"Required by Microsoft Graph for search queries."}},"required":["search"]}, blockHint: 'search-results' as const },
    { name: 'updateListItem', description: 'Update fields of an existing ITEM (row/record) in a SharePoint LIST. SharePoint Hierarchy - You are updating at the ITEMS level: - SITE (e.g., \'HR Hiring Test\') - └── LIST (e.g., \'Job Openings\') └─...', inputSchema: {"type":"object","properties":{"siteId":{"type":"string","description":"The unique ID of the SharePoint site (e.g., 'contoso.sharepoint.com,{guid},{guid}')."},"listId":{"type":"string","description":"The unique ID or URL-encoded name of the list containing the item."},"itemId":{"type":"string","description":"The unique ID of the list item to update (numeric ID as string, e.g., '1', '42')."},"fields":{"type":"object","description":"Request body: Key-value pairs of internal column names and their new values. Only include the specific fields you want to update - unchanged fields..."},"ifMatch":{"type":"string","description":"Optional HTTP header for concurrency control. Use '*' to force update regardless of changes, or provide a specific ETag value (from previous GET) t..."}},"required":["siteId","listId","itemId","fields"]}, blockHint: 'info-card' as const }
  ]
};
