/**
 * SharePoint & OneDrive MCP Server catalog entry.
 * Generated from discovery-output.json — 17 tools.
 * Source of truth: MCP protocol discovery, not guesses.
 */

import type { IMcpCatalogEntry } from '../McpServerCatalog';
import { GATEWAY_BASE } from './constants';

export const ODSP_SERVER: IMcpCatalogEntry = {
  id: 'mcp_ODSPRemoteServer',
  name: 'SharePoint & OneDrive',
  description: 'File/folder CRUD, site discovery, sharing, sensitivity labels',
  scope: 'McpServers.OneDriveSharepoint.All',
  urlTemplate: `${GATEWAY_BASE}/mcp_ODSPRemoteServer`,
  tools: [
    { name: 'getFolderChildren', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Enumerates Top 20 files and folders (DriveItems) contained within a specified parent folder in a Document Library...', inputSchema: {"type":"object","properties":{"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the parent folder"},"parentFolderId":{"type":"string","description":"ID of the parent folder (DriveItem) whose files and folders will be listed.Defaults to the root folder of the Document Library if not specified."}},"required":["documentLibraryId"]}, blockHint: 'document-library' as const },
    { name: 'readSmallTextFile', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Read i.e. download a text file of size less than 5MB from a specific Document Library (or Drive).You need to prov...', inputSchema: {"type":"object","properties":{"fileId":{"type":"string","description":"The ID of the file (DriveItem) to read or download."},"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the file you want to read or download."}},"required":["fileId","documentLibraryId"]}, blockHint: 'file-preview' as const },
    { name: 'listDocumentLibrariesInSite', description: 'List Document Libraries (also called Drives) in the specified Sharepoint Site.If not specified, the root site will be used.', inputSchema: {"type":"object","properties":{"siteId":{"type":"string"}}}, blockHint: 'document-library' as const },
    { name: 'createFolder', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Create a new folder (represented as a DriveItem) within a specified Document Library (also referred to as a Drive...', inputSchema: {"type":"object","properties":{"folderName":{"type":"string","description":"Name of the folder to be created.If a folder with the same name already exists, a numeric suffix will be added to the new folder name(e.g., NewFold..."},"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the folder you want to create"},"parentFolderId":{"type":"string","description":"The ID of the parent folder under which the new folder will be created.Defaults to the root of the document library if not specified."}},"required":["folderName","documentLibraryId"]}, blockHint: 'info-card' as const },
    { name: 'deleteFileOrFolder', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Delete a file or a folder (also referred to as DriveItems) from a specified Document Library (also referred to as...', inputSchema: {"type":"object","properties":{"documentLibraryId":{"type":"string"},"fileOrFolderId":{"type":"string"}},"required":["documentLibraryId","fileOrFolderId"]}, blockHint: 'info-card' as const },
    { name: 'createSmallTextFile', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Create or upload a text file of size less than 5MB to a specific Document Library (or Drive).You can upload it to...', inputSchema: {"type":"object","properties":{"filename":{"type":"string","description":"Name of the file to create including the file extension."},"contentText":{"type":"string","description":"The text content of the file."},"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the file you want to create."},"parentfolderId":{"type":"string","description":"The ID of the parent folder where the file will be created.Defaults to the root folder of the Document Library if not specified."}},"required":["filename","contentText","documentLibraryId"]}, blockHint: 'info-card' as const },
    { name: 'moveSmallFile', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Move a file (also referred to as a DriveItem) located in a specified Document Library (also referred to as a Driv...', inputSchema: {"type":"object","properties":{"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the file you want to move"},"fileId":{"type":"string"},"newParentFolderId":{"type":"string","description":"The ID of the target folder to move the file into.Should be in the same document library as the original location of the file."}},"required":["documentLibraryId","fileId","newParentFolderId"]}, blockHint: 'info-card' as const },
    { name: 'findSite', description: 'Find Sharepoint Sites accessible to the user.This tool can either find specific site based on a search query you pass itOr find the top 20 relevant sites accesible by the user if you don\'t pass it ...', inputSchema: {"type":"object","properties":{"searchQuery":{"type":"string","description":"Search query could be the entire or partial site name.Passing in a search query will help efficiently search for a file, but only do so if the user..."}}}, blockHint: 'search-results' as const },
    { name: 'createSmallBinaryFile', description: 'Create a binary file of size less than 5MB by base64 encoding its content to a specific Document Library (or Drive).You can create it in a specific folder on the DocumentLibrary.If no folder is spe...', inputSchema: {"type":"object","properties":{"filename":{"type":"string","description":"Name of the file to create including the file extension."},"base64Content":{"type":"string","description":"The binary file content encoded as a base64 string."},"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) where you want to create the file."},"parentfolderId":{"type":"string","description":"The ID of the parent folder where the file will be created.Defaults to the root folder of the Document Library if not specified."}},"required":["filename","base64Content","documentLibraryId"]}, blockHint: 'info-card' as const },
    { name: 'getFileOrFolderMetadata', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Get metadata of a file or a folder (also referred to as DriveItems) from a specified Document Library (also refer...', inputSchema: {"type":"object","properties":{"fileOrFolderId":{"type":"string","description":"Id of a file or a folder.They are also called DriveItems.And their Id can also be sometimes referred to as a driveItemId."},"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the file or folder that you need the metadata of."}},"required":["fileOrFolderId","documentLibraryId"]}, blockHint: 'file-preview' as const },
    { name: 'findFileOrFolder', description: 'Finds a file or a folder (also called as a DriveItem) accessible to a user by passing a search query.', inputSchema: {"type":"object","properties":{"searchQuery":{"type":"string","description":"Search query could be the entire or partial file name."}},"required":["searchQuery"]}, blockHint: 'search-results' as const },
    { name: 'getDefaultDocumentLibraryInSite', description: 'Get the default Document Library (also called Drive) in a Sharepoint Site.If not specified, the root site will be used.', inputSchema: {"type":"object","properties":{"siteId":{"type":"string"}}}, blockHint: 'document-library' as const },
    { name: 'setSensitivityLabelOnFile', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Set the sensitivity label of a file (specified by the fileId also called driveItemId) from the specified Document...', inputSchema: {"type":"object","properties":{"documentLibraryId":{"type":"string","description":"The document library id also known as driveId of the document library"},"fileId":{"type":"string","description":"The file id also known as driveItemId of the file"},"sensitivityLabelId":{"type":"string","description":"Required. ID of the sensitivity label to be assigned, or empty string to remove the sensitivity label."},"assignmentMethod":{"type":"string","description":"Optional. The assignment method of the label on the document.Indicates whether the assignment of the label was done automatically, standard, or as ..."},"justificationText":{"type":"string","description":"Optional. Justification text for audit purposes, and is required when downgrading/removing a label."}},"required":["documentLibraryId","fileId","sensitivityLabelId"]}, blockHint: 'info-card' as const },
    { name: 'shareFileOrFolder', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Sends a sharing invitation to grant read/write permissions on a file or folder (DriveItem) within a specified Doc...', inputSchema: {"type":"object","properties":{"documentLibraryId":{"type":"string","description":"ID of the Document Library (Drive) containing the file or folder to share."},"fileOrFolderId":{"type":"string","description":"ID of the file or folder (DriveItem) to share."},"recipientEmails":{"type":"array","description":"Email addresses of recipients to invite.At least one recipient email is required.","items":{"type":"string"}},"roles":{"type":"array","description":"Roles to assign to recipients.Accepted values: read, write (write grants both read and write access).Defaults to read role if not specified.","items":{"type":"string"}},"sendInvitation":{"type":"boolean","description":"Indicates whether to send a sharing invitation.Defaults to true if not specified."},"message":{"type":"string","description":"Custom message to include in the invitation email.Defaults to a standard message if not specified."}},"required":["documentLibraryId","fileOrFolderId","recipientEmails","roles"]}, blockHint: 'info-card' as const },
    { name: 'readSmallBinaryFile', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Read a binary file of size less than 5MB from a specific Document Library (or Drive).You need to provide a fileId...', inputSchema: {"type":"object","properties":{"fileId":{"type":"string","description":"The ID of the file (DriveItem) to read or download."},"documentLibraryId":{"type":"string","description":"Id of the Document Library (also called as a Drive) of the file you want to read or download."}},"required":["fileId","documentLibraryId"]}, blockHint: 'file-preview' as const },
    { name: 'getFileOrFolderMetadataByUrl', description: 'Get metadata of a file or a folder (also referred to as DriveItems) from a sharing URL.Only users with existing explicit permissions to access the file will be allowed to get the metadata of the file.', inputSchema: {"type":"object","properties":{"fileOrFolderUrl":{"type":"string","description":"Url of the File or Folder (also referred to as DriveItems).The url will not be redeemed to share it with the user, they must already have explicit ..."}},"required":["fileOrFolderUrl"]}, blockHint: 'file-preview' as const },
    { name: 'renameFileOrFolder', description: 'Use this tool for SharePoint document libraries or when you need to specify a drive.Rename a file or a folder (also referred to as DriveItems) within a specified Document Library (also referred to ...', inputSchema: {"type":"object","properties":{"documentLibraryId":{"type":"string"},"fileOrFolderId":{"type":"string"},"newFileOrFolderName":{"type":"string"}},"required":["documentLibraryId","fileOrFolderId","newFileOrFolderName"]}, blockHint: 'info-card' as const }
  ]
};
