/**
 * Microsoft Teams MCP Server catalog entry.
 * Generated from discovery-output.json — 26 tools.
 * Source of truth: MCP protocol discovery, not guesses.
 */

import type { IMcpCatalogEntry } from '../McpServerCatalog';
import { GATEWAY_BASE } from './constants';

export const TEAMS_SERVER: IMcpCatalogEntry = {
  id: 'mcp_TeamsServer',
  name: 'Microsoft Teams',
  description: 'Chats, channels, teams, members, and messages',
  scope: 'McpServers.Teams.All',
  urlTemplate: `${GATEWAY_BASE}/mcp_TeamsServer`,
  tools: [
    { name: 'ListTeams', description: 'List Microsoft Teams workspaces (collaboration spaces with channels) that a user is a member of. Use for Teams channel operations. ⚠️ TOOL DEPENDENCY RULE: you MUST call the User Lookup tool FIRST ...', inputSchema: {"type":"object","properties":{"userId":{"type":"string","description":"ID of the user whose teams are to be retrieved. If this is not known at the time the request is being made, use the appropriate tool to get my deta..."},"accept":{"type":"string","description":"Acceptable MIME type of the response."}},"required":["userId"]}, blockHint: 'selection-list' as const },
    { name: 'ListChats', description: 'List Teams chats by metadata. ⚠️ TOOL DEPENDENCY RULE: If the user request references a person (name, alias, email fragment, \'my chat with X\', etc.), you MUST call the User Lookup tool FIRST to obt...', inputSchema: {"type":"object","properties":{"userUpns":{"type":"array","description":"Array of strings filter to return only chats where the specified user(s) are members. This field should never be created by the model. When the UPN...","items":{"type":"string"}},"topic":{"type":"string","description":"String filter to return only chats with specified topic(s). When chat topic(s) are known and relevant to the intent, this filter SHOULD be provided..."},"top":{"type":"object"}},"required":["userUpns"]}, blockHint: 'selection-list' as const },
    { name: 'ListChannels', description: 'Lists channels in a Microsoft Teams team.🔒 REQUIRED TOOL CHAIN: Before calling this tool, you MUST first call the ListTeams tool to retrieve the correct teamId (GUID). This tool CANNOT be used wit...', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"REQUIRED. The teamId GUID returned from the ListTeams tool. This is a SYSTEM-DERIVED IDENTIFIER. It must be copied from the 'id' field of a ListTea..."},"select":{"type":"string","description":"Comma-separated list of fields to return (e.g., 'sender,subject,createdDateTime')."},"filter":{"type":"string","description":"OData filter expression (e.g., \"createdDateTime ge 2025-08-01T00:00:00Z\")."}},"required":["teamId"]}, blockHint: 'selection-list' as const },
    { name: 'ListChatMessages', description: 'List messages in a chat. Use when needing to inspect chat history. Returns most recent messages first.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat the messages are to be listed from. If this is not known at the time the request is being made, use the listChats tool to retrieve t..."},"top":{"type":"object"},"filter":{"type":"string","description":"OData filter expression (e.g., \"createdDateTime ge 2025-08-01T00:00:00Z\")."},"orderby":{"type":"string","description":"Sort expression (e.g., 'createdDateTime desc')."}},"required":["chatId"]}, blockHint: 'list-items' as const },
    { name: 'ListChannelMessages', description: 'List messages in a channel. Use when needing to inspect channel history. Returns most recent messages first.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team where the channel the messages to be listed from is in. If this is not known at the time the request is being made, use the listTeam..."},"channelId":{"type":"string","description":"ID of the channel the messages are to be listed from. If this is not known at the time the request is being made, use the listChannels tool to retr..."},"top":{"type":"object"},"expand":{"type":"string","description":"Comma-separated list of fields to expand (e.g replies, mentions)."}},"required":["teamId","channelId"]}, blockHint: 'list-items' as const },
    { name: 'PostMessage', description: 'Send a message to an existing chat. If the chat ID isn\'t provided, you MUST first find or create the chat using ListChats or CreateChat. Supports plain text or HTML. Send exactly what the user type...', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat to send the message in. If this is not known at the time the request is being made, use the listChats tool to retrieve the relevant ..."},"content":{"type":"string","description":"The message text content"},"contentType":{"type":"string","description":"Type of content. Possible values are 'text' and 'html'."}},"required":["chatId","content"]}, blockHint: 'info-card' as const },
    { name: 'PostChannelMessage', description: 'Post a message to a team channel. Supports plain text or HTML. Send exactly what the user typed without re-formatting unless explicitly requested.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team where the channel the message to be sent in is in. If this is not known at the time the request is being made, use the listTeams too..."},"channelId":{"type":"string","description":"ID of the channel the message is to be sent in. If this is not known at the time the request is being made, use the listChannels tool to retrieve t..."},"content":{"type":"string","description":"The message text content"},"contentType":{"type":"string","description":"Type of content. Possible values are 'text' and 'html'."}},"required":["teamId","channelId","content"]}, blockHint: 'info-card' as const },
    { name: 'GetTeam', description: 'Get details of a Microsoft Teams workspace. 🔒 REQUIRED TOOL CHAIN: Before calling this tool, you MUST first call the ListTeams tool to retrieve the correct teamId (GUID). This tool cannot be used ...', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"REQUIRED. The teamId GUID returned from the ListTeams tool. This is a SYSTEM-DERIVED IDENTIFIER and must be copied from the 'id' field of a ListTea..."},"select":{"type":"string","description":"Comma-separated list of fields to return (e.g., 'sender,subject,createdDateTime')."},"expand":{"type":"string","description":"Comma-separated list of fields to expand (e.g replies, mentions)."}},"required":["teamId"]}, blockHint: 'info-card' as const },
    { name: 'GetChat', description: 'Get details of a specific chat by ID.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat to retrieve. Must be in thread.v2 format."}},"required":["chatId"]}, blockHint: 'info-card' as const },
    { name: 'CreateChat', description: 'Create a new chat. For one-on-one chats, provide 2 user IDs. For group chats, provide a topic and 2 or more user IDs.', inputSchema: {"type":"object","properties":{"chatType":{"type":"string","description":"Type of the chat to be created i.e oneOnOne or group."},"members_upns":{"type":"array","description":"String array of real, verified user UPN email strings. Never guess or fabricate UPNs and never use values like 'me', 'me@*', placeholders, or examp...","items":{"type":"string"}},"topic":{"type":"string","description":"The title of the chat. The chat title can be provided only if the chat is of group type."},"contenttype":{"type":"string","description":"MIME type of the upload"}},"required":["chatType","members_upns"]}, blockHint: 'info-card' as const },
    { name: 'DeleteChat', description: 'Delete a chat by ID.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat to be deleted. If this is not known at the time the request is being made, use the listChats tool to retrieve the relevant chat and ..."}},"required":["chatId"]}, blockHint: 'info-card' as const },
    { name: 'UpdateChat', description: 'Update a chat\'s topic.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat to be updated. If this is not known at the time the request is being made, use the listChats tool to retrieve the relevant chat and ..."},"topic":{"type":"string","description":"The display name of the chat to be updated (group chat). This API can only be called on groupchats only."},"contenttype":{"type":"string","description":"MIME type of the upload"}},"required":["chatId","topic"]}, blockHint: 'info-card' as const },
    { name: 'GetChannel', description: 'Get details of a specific channel by ID.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team the channel is to be retrieved from. If this is not known at the time the request is being made, use the listTeams tool to retrieve ..."},"channelId":{"type":"string","description":"ID of the channel to be retrieved from the team. If this is not known at the time the request is being made, use the listChannels tool to retrieve ..."},"select":{"type":"string","description":"Comma-separated list of fields to return (e.g., 'sender,subject,receivedDateTime')."},"filter":{"type":"string","description":"OData filter expression (e.g., \"receivedDateTime ge 2025-08-01T00:00:00Z\")."}},"required":["teamId","channelId"]}, blockHint: 'info-card' as const },
    { name: 'CreateChannel', description: 'Creates a new channel in a Microsoft Teams team.🔒 REQUIRED TOOL CHAIN: Before calling this tool, you MUST first call the ListTeams tool to retrieve the correct teamId (GUID). This tool cannot be u...', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"REQUIRED. The teamId GUID returned from the ListTeams tool. This is a SYSTEM-DERIVED IDENTIFIER and must be copied from the 'id' field of a ListTea..."},"displayName":{"type":"string","description":"Name of the channel to be displayed to end users."},"description":{"type":"string","description":"Description of the channel."}},"required":["teamId","displayName"]}, blockHint: 'info-card' as const },
    { name: 'CreatePrivateChannel', description: 'Create a new private channel in a team.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team the channel is to be created in. If this is not known at the time the request is being made, use the listTeams tool to retrieve the ..."},"displayName":{"type":"string","description":"Name of the channel to be displayed to end users."},"description":{"type":"string","description":"Description of the channel."}},"required":["teamId","displayName"]}, blockHint: 'info-card' as const },
    { name: 'UpdateChannel', description: 'Update a channel\'s display name and/or description.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team where the channel is to be updated. If this is not known at the time the request is being made, use the listTeams tool to retrieve t..."},"channelId":{"type":"string","description":"ID of the channel to be updated. If this is not known at the time the request is being made, use the listChannels tool to retrieve the relevant cha..."},"displayName":{"type":"string","description":"Name of the channel to be displayed to end users."},"description":{"type":"string","description":"Description of the channel."}},"required":["teamId","channelId"]}, blockHint: 'info-card' as const },
    { name: 'ListChatMembers', description: 'List all members of a chat.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat whose members are to be listed from. If this is not known at the time the request is being made, use the listChats tool to retrieve ..."}},"required":["chatId"]}, blockHint: 'selection-list' as const },
    { name: 'ListChannelMembers', description: 'List all members of a channel.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team where the channel the members to be listed from is in. If this is not known at the time the request is being made, use the listTeams..."},"channelId":{"type":"string","description":"ID of the channel the members are to be listed from. If this is not known at the time the request is being made, use the listChannels tool to retri..."},"top":{"type":"object"},"expand":{"type":"string","description":"Comma-separated list of fields to expand."}},"required":["teamId","channelId"]}, blockHint: 'selection-list' as const },
    { name: 'AddChatMember', description: 'Add a member to an existing chat.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat the member is to be added to. If this is not known at the time the request is being made, use the listChats tool to retrieve the rel..."},"roles":{"type":"array","description":"The role of the member to be added, as a string array. In all cases, specify 'owner' for every member other than an in-tenant guest user, who must ...","items":{"type":"string"}},"userodata_bind":{"type":"string","description":"A reference to the user, by ID or UPN. Should follow the format 'https://graph.microsoft.com/v1.0/users('USER_GUID_OR_UPN')'. Do NOT pass the value..."},"contenttype":{"type":"string","description":"MIME type of the upload"},"odata_type":{"type":"string","description":"The type of entity in the response payload. Constant value '#microsoft.graph.aadUserConversationMember'."}},"required":["chatId","roles","userodata_bind"]}, blockHint: 'info-card' as const },
    { name: 'AddChannelMember', description: 'Add a member to a channel.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team the channel is to have a new member added to. If this is not known at the time the request is being made, use the listTeams tool to ..."},"channelId":{"type":"string","description":"ID of the channel a new member is to be added to. If this is not known at the time the request is being made, use the listChannels tool to retrieve..."},"userId":{"type":"string","description":"The user ID (GUID) to add to the channel. If this is not known at the time the request is being made, get the user details from the relevant tool t..."}},"required":["teamId","channelId","userId"]}, blockHint: 'info-card' as const },
    { name: 'GetChatMessage', description: 'Get details of a specific message in a chat.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat the message is to be retrieved from. If this is not known at the time the request is being made, use the listChats tool to retrieve ..."},"messageId":{"type":"string","description":"ID of the chat message to be retrieved. If this is not known at the time the request is being made, use the listChatMessages tool to retrieve the r..."}},"required":["chatId","messageId"]}, blockHint: 'markdown' as const },
    { name: 'UpdateChatMessage', description: 'Update the content of a message in a chat.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat where the message is to be updated. If this is not known at the time the request is being made, use the listChats tool to retrieve t..."},"messageId":{"type":"string","description":"ID of the chat message to be updated. If this is not known at the time the request is being made, use the listChatMessages tool to retrieve the rel..."},"content":{"type":"string","description":"The message text content"}},"required":["chatId","messageId","content"]}, blockHint: 'info-card' as const },
    { name: 'DeleteChatMessage', description: 'Delete a message from a chat.', inputSchema: {"type":"object","properties":{"chatId":{"type":"string","description":"ID of the chat the message is to be deleted in. If this is not known at the time the request is being made, use the listChats tool to retrieve the ..."},"messageId":{"type":"string","description":"ID of the chat message to be deleted. If this is not known at the time the request is being made, use the listChatMessages tool to retrieve the rel..."}},"required":["chatId","messageId"]}, blockHint: 'info-card' as const },
    { name: 'ReplyToChannelMessage', description: 'Reply to a specific message in a channel.', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team where the channel the reply is to be sent to. If this is not known at the time the request is being made, use the listTeams tool to ..."},"channelId":{"type":"string","description":"ID of the channel the reply is to be sent to. If this is not known at the time the request is being made, use the listChannels tool to retrieve the..."},"messageId":{"type":"string","description":"ID of the message to reply to"},"content":{"type":"string","description":"The reply content"},"contentType":{"type":"string","description":"The content type: 'text' or 'html' (default: 'text')"}},"required":["teamId","channelId","messageId","content"]}, blockHint: 'info-card' as const },
    { name: 'UpdateChannelMember', description: 'Update a channel member\'s role (owner or member).', inputSchema: {"type":"object","properties":{"teamId":{"type":"string","description":"ID of the team where the channel is to have a member updated. If this is not known at the time the request is being made, use the listTeams tool to..."},"channelId":{"type":"string","description":"ID of the channel where a member is to be updated. If this is not known at the time the request is being made, use the listChannels tool to retriev..."},"membershipId":{"type":"string","description":"The user ID (GUID) to add to the channel. If this is not known at the time the request is being made, get the user details from the relevant tool t..."},"role":{"type":"string","description":"The role of the member to be updated, as a string. Must be 'owner' or 'member'."}},"required":["teamId","channelId","membershipId","role"]}, blockHint: 'info-card' as const },
    { name: 'SearchTeamsMessages', description: 'Search Microsoft Teams chats and channel messages using natural language (e.g., \'messages from John about the project\', \'recent messages in Marketing team\', \'unread messages from last week\'). Retur...', inputSchema: {"type":"object","properties":{"message":{"type":"string","description":"Natural language search query for finding Teams messages (e.g., 'messages from John about the project', 'unread messages from last week in the Engi..."},"conversationId":{"type":"string","description":"Existing conversation id (GUID). Auto-created if missing."}},"required":["message"]}, blockHint: 'list-items' as const }
  ]
};
